### ISSUE TITLE
Do not use Neo Euler yet

### ISSUE THREAD

**Issue by khaledhosny** [fred-wang/MathFonts#1]
I fear that the Neo Euler font is incomplete and it has been pending an overhaul for a while, so better not to publicize it just yet.

**Comment by fred-wang** [comment]
FYI, I removed Neo Euler and other math fonts that are "not ready" for now.

**Comment by khaledhosny** [comment]
FWIW, I’m no longer working on this font. GUST might be working on an alternative, but I don’t have any details.
