### ISSUE TITLE
Surd in Latin Modern

### ISSUE THREAD

**Issue by ronkok** [fred-wang/MathFonts#11]
The Latin Modern font is nearly flawless, but it has one problem. The surd character, √ (U+221A), has the wrong vertical alignment when written in a `<mi>` element. This can be verified by using Firefox to view [this example](https://temml.org/#A%20%5Csurd%20B) or row 31 on [this test page](https://temml.org/tests/wiki-tests.html).

Other math fonts render `<mi>√</mi>` just fine.

On the other hand, the Latin Modern surd works very well in the `<msqrt>` element.

I looked at http://www.gust.org.pl/projects/e-foundry/ but I could not find a place there to write this issue. In fact, I could not find any `woff` version of the font. If you feel that this issue should be raised there and not here, maybe you could give me a hint about just where the issue should be raised?

**Comment by fred-wang** [comment]
Unless something goes wrong with the woff conversion, I guess this is either a Latin Modern Math font problem or a browser bug. Perhaps you should try with the original otf font with modern LaTeX engines and report to the GUST group. Unfortunately, I'm not sure they have any public bug tracker...

**Comment by ronkok** [comment]
Follow up: I could not find a `woff` or `woff2` version of the font at the GUST foundry. Only OTF and native TeX font files.

But I did find a `latin-modern-math.woff2` file at https://github.com/giancarloantonucci/latin-modern. It's surd character renders at the proper elevation. In all other respects, it appears to be the same font. Please consider updating the Latin Modern file in this repository.

Off-topic, I see recent progress in Chromium Canary's rendering of MathML. I'm looking forward to the day when MathML renders in all browsers and I want to thank you for your efforts.

**Comment by fred-wang** [comment]
OK, good to know. Are you able to provide the version numbers of the different font files you found?

**Comment by ronkok** [comment]
I don't see a version number anywhere. I suppose one track using a GitHub commit hash.

**Comment by fred-wang** [comment]
It's encoded inside the font. For example the one in this repo is 1.959: https://fred-wang.github.io/MathFonts/LatinModern/index.html

which is the same version mentioned here: https://www.gust.org.pl/projects/e-foundry/lm-math/download/index_html

**Comment by ronkok** [comment]
Ah yes. Now that I look inside the `woff2` font from the other repository, I see that its version number is also 1.959.

On the other hand, it is not a copy of the same file. The one from the other repository is 383 KB and the one from this repository is 379 KB.

**Comment by ronkok** [comment]
Oops. I have to correct an error. I had a typo in the CSS and I was not rendering the Latin Modern font. I was probably looking at the local Cambria Math. When I correct the CSS typo, the font file from the other repository has the same surd problem as the file in this repository.

Sorry for the confusion. I guess I'll have to load the OTF somehow and test it.

**Comment by ronkok** [comment]
The surd alignment problem also occurs in LaTeX. See the discussion at https://tex.stackexchange.com/questions/636039/strange-position-of-unicode-square-root-glyph-u221a-in-latin-modern-math.

This is a GUST problem. Not much can be done about it here, so I will close this issue.

**Comment by fred-wang** [comment]
OK. Thanks for your investigation!
