### ISSUE TITLE
Broken link in the extension’s description

### ISSUE THREAD

**Issue by pepelsbey** [fred-wang/MathFonts#13]
It goes like this:

> It is strongly recommended to read [the instructions for MathML fonts](https://developer.mozilla.org/en-US/Mozilla_MathML_Project/Fonts) before trying to install this add-on.

- And links to https://developer.mozilla.org/en-US/Mozilla_MathML_Project/Fonts
- Which is now https://developer.mozilla.org/en-US/docs/Web/MathML/Fonts

We should probably redirect such URLs on MDN, but this one is missing from the config, unfortunately.

**Comment by fred-wang** [comment]
Thanks!

https://addons.mozilla.org/en-US/firefox/addon/mathml-fonts/ fixed
