### ISSUE TITLE
Add WOFF 2 Web Fonts

### ISSUE THREAD

**Issue by fred-wang** [fred-wang/MathFonts#3]
To consider when WOFF 2 is more popular.

**Comment by khaledhosny** [comment]
Both Firefox and Chrome support WOFF 2 now, and I think math fonts can benefit greatly given their relatively big file sizes (I didn’t do any measurements, though).

**Comment by fred-wang** [comment]
Yes, my concern is WOFF2 support in WebKit, especially the Mac/iOS and GTK ports:
https://bugs.webkit.org/show_bug.cgi?id=152616
https://bugs.webkit.org/show_bug.cgi?id=150830

I can however already provide WOFF2 versions, even if they are not used by the demo pages.

**Comment by fred-wang** [comment]
OK, WOFF2 fonts are now included. The CSS stylesheets try WOFF2 first and WOFF otherwise. For math fonts, it seems that you win ~50-100kb by using WOFF2 instead of WOFF.

**Comment by khaledhosny** [comment]
You might want to transcode the original fonts with FontTools, this usually results in smaller file size due to FontTools choosing more compact OpenType representation.

**Comment by fred-wang** [comment]
Thanks for the info. However, I'm not sure whether the RFN clause applies for such transformations...

**Comment by khaledhosny** [comment]
My guess it is no different than WOFF2 transformations, but that can be a violation to RFN as well.

**Comment by fred-wang** [comment]
Well, yes now that you mention it I suspect the WOFF2 transformations violate OFL's RFN clause because you can not preserve the original binary data :-( Probably, this should be raised to OFL / WOFF2 orgs... Maybe they can clarify that the WOFF2 / FontTools transforms are "acceptable".

**Comment by fred-wang** [comment]
So I was thinking about http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#1db14da7 that says that "the original font data remains unchanged except for WOFF compression".

However, reading the less strict concept of "Functional Equivalence" in
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web_fonts_and_RFNs
WOFF2 and FontTools transformations are likely to be acceptable changes.
