### ISSUE TITLE
Include Svobodny fonts

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [fred-wang/MathFonts#9]
Recently Aleksandr Andreev plan to release Svobodny fonts, which derived from GNU FreeFont, and intended to intergrate improves from uptream, also including Math table, so filing this to track.

The source codes are available here: https://github.com/typiconman/fonts-cu/tree/master/Svobodny

**Comment by fred-wang** [comment]
@KrasnayaPloshchad Link is broken?

**Comment by KrasnayaPloshchad** [comment]
I saw that repo again and I found the fonts were gone, so the author abandoned.
